In [5]:
import time
import pandas as pd
import numpy as np

In [6]:
CITY_DATA = { 'chicago': 'chicago.csv',
              'new york city': 'new_york_city.csv',
              'washington': 'washington.csv' }

In [7]:
def validate_entry(value,valid_values,type_validation):
    
    while value not in valid_values:
        if value == '':
            value = input('Write a {}: '.format(type_validation))
        else:
            value = input('Write a {}: '.format(type_validation))
        value = value.lower()
        
    return value


def get_filters():
    """
    Asks user to specify a city, month, and day to analyze.

    Returns:
        (str) city - name of the city to analyze
        (str) month - name of the month to filter by, or "all" to apply no month filter
        (str) day - name of the day of week to filter by, or "all" to apply no day filter
    """
    print('Hello! Let\'s explore some US bikeshare data!')
    
    
      # TO DO: get user input for city (chicago, new york city, washington). HINT: Use a while loop to handle invalid inputs

    
    #while city not in valid_cities: # 1a opcion .lower() lo usamos aquí solamente para poder comparar
     #   if city == '':
        #    city = input('Write a city: ') #si pongo : fuera del '' dara error // 2na opcion .lower() aquí modifica el valor que ha escrito
      #  else:
      #      city = input('Write a valid city, PLEASE: ')
      #  city = city.lower()    #3era opcion: asignamos que la variable city sea minuscula y solo usamos lower() 1 vez (por fuera del if)

    # TO DO: get user input for month (all, january, february, ... , june)

    # TO DO: get user input for day of week (all, monday, tuesday, ... sunday)
    
    city = ''
    
    month = ''
    
    day = ''
    
    valid_cities = ['chicago', 'new york city', 'washington']
    
    valid_months = ['january', 'february', 'march', 'april', 'may', 'june', 'all']
    
    valid_days = ['monday','tuesday','wednesday','thursday','friday','saturday','sunday','all']
    
    month = validate_entry(month,valid_months,'month')
    
    day = validate_entry(day,valid_days,'day')
    
    city = validate_entry(city,valid_cities,'city')
    
    
    # TO DO: get user input for city (chicago, new york city, washington). HINT: Use a while loop to handle invalid inputs

    
    #while city not in valid_cities: # 1a opcion .lower() lo usamos aquí solamente para poder comparar
     #   if city == '':
        #    city = input('Write a city: ') #si pongo : fuera del '' dara error // 2na opcion .lower() aquí modifica el valor que ha escrito
      #  else:
      #      city = input('Write a valid city, PLEASE: ')
      #  city = city.lower()    #3era opcion: asignamos que la variable city sea minuscula y solo usamos lower() 1 vez (por fuera del if)

    # TO DO: get user input for month (all, january, february, ... , june)

    # TO DO: get user input for day of week (all, monday, tuesday, ... sunday)
    
    print('-'*40)
    return city, month, day

In [17]:
def load_data(city, month, day):
    """
    Loads data for the specified city and filters by month and day if applicable.

    Args:
        (str) city - name of the city to analyze
        (str) month - name of the month to filter by, or "all" to apply no month filter
        (str) day - name of the day of week to filter by, or "all" to apply no day filter
    Returns:
        df - Pandas DataFrame containing city data filtered by month and day
    """
    global CITY_DATA
    
    # load dataframe acourding to city
    df = pd.read_csv('./datasets/' + CITY_DATA[city])
    
    df['Start Time'] = pd.to_datetime(df['Start Time'])
    
    months = {
        1: 'january',
        2: 'february',
        3: 'march',
        4: 'april',
        5: 'may', 
        6: 'june'        
    }
    
    df['month'] = df['Start Time'].dt.month.map(months)
    df['day'] = df['Start Time'].dt.day_name()
    
    
    if day != 'all':
        df = df[df['day'] == day.capitalize()] # Monday  ---- monday.capitalize() -> Monday
        
    if month != 'all':
        df = df[df['month'] == month]       

    return df

In [11]:
def time_stats(df):
    """Displays statistics on the most frequent times of travel."""

    print('\nCalculating The Most Frequent Times of Travel...\n')
    start_time = time.time()

    # TO DO: display the most common month
    most_common_month = df['month'].mode()
    print('The most common month is {}'.format(most_common_month[0]))

    # TO DO: display the most common day of week
    most_common_day = df['day'].mode()
    print('The most common day of week is {}'.format(most_common_day[0]))
    
    # TO DO: display the most common start hour
    most_common_hour = df['Start Time'].dt.hour.mode()
    print('The most common start hour is {}'.format(most_common_hour[0]))


    print("\nThis took %s seconds." % (time.time() - start_time))
    print('-'*40)

In [18]:
data = load_data('chicago', 'all', 'monday')
data.head()

,Unnamed: 0,Start Time,End Time,Trip Duration,Start Station,End Station,User Type,Gender,Birth Year,month,day
3,304487,2017-03-06 13:49:38,2017-03-06 13:55:28,350,Christiana Ave & Lawrence Ave,St. Louis Ave & Balmoral Ave,Subscriber,Male,1986.0,march,Monday
5,1473887,2017-06-26 09:01:20,2017-06-26 09:11:06,586,Clinton St & Washington Blvd,Canal St & Taylor St,Subscriber,Male,1990.0,june,Monday
9,135470,2017-02-06 18:00:47,2017-02-06 18:09:00,493,Stetson Ave & South Water St,Clinton St & Washington Blvd,Subscriber,Male,1979.0,february,Monday
32,1359055,2017-06-19 17:43:17,2017-06-19 17:59:35,978,Larrabee St & Armitage Ave,Dearborn Pkwy & Delaware Pl,Subscriber,Female,1993.0,june,Monday
36,165328,2017-02-13 14:17:25,2017-02-13 14:22:52,327,University Ave & 57th St,Kimbark Ave & 53rd St,Subscriber,Female,1984.0,february,Monday

In [40]:
def station_stats(df):
    """Displays statistics on the most popular stations and trip."""

    print('\nCalculating The Most Popular Stations and Trip...\n')
    start_time = time.time()

    # TO DO: display most commonly used start station
    
    most_common_start_station = df['Start Station'].mode()
    print('The most common start_station is {}'.format(most_common_start_station[0]))


    # TO DO: display most commonly used end station
    
    most_common_end_station = df['End Station'].mode()
    print('The most common end_station is {}'.format(most_common_end_station[0]))


    # TO DO: display most frequent combination of start station and end station trip
    df_station = df.groupby(['Start Station', 'End Station']).count()
    df_station = df_station['Start Time']
    start_end_station = df_station.idxmax()
    print('The most frequent combination of start station and end station trip is {}'
          .format(start_end_station))

    print("\nThis took %s seconds." % (time.time() - start_time))
    print('-'*40)

In [41]:
station_stats(df)

Calculating The Most Popular Stations and Trip...

The most common start_station is 0    Streeter Dr & Grand Ave
dtype: object
The most common end_station is 0    Streeter Dr & Grand Ave
dtype: object
The most frequent combination of start station and end station trip is ('Lake Shore Dr & Monroe St', 'Streeter Dr & Grand Ave')

This took 0.0849466323852539 seconds.
----------------------------------------

In [50]:
def trip_duration_stats(df):
    """Displays statistics on the total and average trip duration."""

    print('\nCalculating Trip Duration...\n')
    start_time = time.time()

    # TO DO: display total travel time
    total_travel_time = df['Trip Duration'].sum()
    print('The total travel time is {} seconds'.format(total_travel_time))

    # TO DO: display mean travel time
    mean_travel_time = df['Trip Duration'].mean()
    print('The mean travel time is {} seconds'.format(mean_travel_time))

    print("\nThis took %s seconds." % (time.time() - start_time))
    print('-'*40)

In [51]:
trip_duration_stats(df)

Calculating Trip Duration...

The total travel time is 39945856 seconds
The mean travel time is 890.039348499365 seconds

This took 0.0019989013671875 seconds.
----------------------------------------

In [74]:
def user_stats(df):
    """Displays statistics on bikeshare users."""

    print('\nCalculating User Stats...\n')
    start_time = time.time()

    # TO DO: Display counts of user types
    type_user_counts = df['User Type'].value_counts()
    print(type_user_counts.reset_index().rename(columns={'index': 'User Type', 
                                                     'User Type': 'Frequency'}))

    # TO DO: Display counts of gender
    gender_counts = df['Gender'].value_counts()
    print(gender_counts.reset_index().rename(columns={'index': 'Gender', 
                                                     'Gender': 'Frequency'}))

    # TO DO: Display earliest, most recent, and most common year of birth
    min_birth = df['Birth Year'].min()
    max_birth = df['Birth Year'].max()
    mode_birth = df['Birth Year'].mode()
    print('year of birth --> Earliest: {}, most recent: {}, most common: {}'.
          format(min_birth, max_birth, mode_birth[0]))

    print("\nThis took %s seconds." % (time.time() - start_time))
    print('-'*40)

In [75]:
user_stats(df)

Calculating User Stats...

    User Type  Frequency
0  Subscriber      37316
1    Customer       7565
   Gender  Frequency
0    Male      28646
1  Female       8689
year of birth --> Earliest: 1899.0, most recent: 2016.0, most common: 1989.0

This took 0.03197765350341797 seconds.
----------------------------------------

In [76]:
def main():
    while True:
        city, month, day = get_filters()
        df = load_data(city, month, day)

        time_stats(df)
        station_stats(df)
        trip_duration_stats(df)
        user_stats(df)

        restart = input('\nWould you like to restart? Enter yes or no.\n')
        if restart.lower() != 'yes':
            break


if __name__ == "__main__":
	main()

Hello! Let's explore some US bikeshare data!
Write a month: all
Write a day: all
Write a city: chicago
----------------------------------------

Calculating The Most Frequent Times of Travel...

The most common month is 0    june
dtype: object
The most common day of week is 0    Tuesday
dtype: object
The most common start hour is 0    17
dtype: int64

This took 0.11822652816772461 seconds.
----------------------------------------

Calculating The Most Popular Stations and Trip...

The most common start_station is 0    Streeter Dr & Grand Ave
dtype: object
The most common end_station is 0    Streeter Dr & Grand Ave
dtype: object
The most frequent combination of start station and end station trip is ('Lake Shore Dr & Monroe St', 'Streeter Dr & Grand Ave')

This took 0.4592270851135254 seconds.
----------------------------------------

Calculating Trip Duration...

The total travel time is 280871787 seconds
The mean travel time is 936.23929 seconds

This took 0.0009996891021728516 seconds.
----------------------------------------

Calculating User Stats...

    User Type  Frequency
0  Subscriber     238889
1    Customer      61110
2   Dependent          1
   Gender  Frequency
0    Male     181190
1  Female      57758
year of birth --> Earliest: 1899.0, most recent: 2016.0, most common: 1989.0

This took 0.08994317054748535 seconds.
----------------------------------------

Would you like to restart? Enter yes or no.
no